# Generated by Django 3.0.8 on 2021-03-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentMethod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('tel', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EnterprisePaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentMethod.PaymentMethod')),
            ],
            options={
                'unique_together': {('enterprise', 'payment_method')},
            },
        ),
        migrations.AddField(
            model_name='enterprise',
            name='payment_methods',
            field=models.ManyToManyField(through='enterprise.EnterprisePaymentMethod', to='paymentMethod.PaymentMethod'),
        ),
        migrations.AlterUniqueTogether(
            name='enterprise',
            unique_together={('longitude', 'latitude')},
        ),
    ]
