# Generated by Django 3.0.8 on 2021-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentMethod', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('tel', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('payment_methods', models.ManyToManyField(to='paymentMethod.PaymentMethod')),
            ],
            options={
                'unique_together': {('longitude', 'latitude')},
            },
        ),
    ]
