# Generated by Django 3.0.8 on 2021-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
