# Generated by Django 3.0.8 on 2021-05-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client_profile'),
        ),
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='worker_profile'),
        ),
    ]
