version: '3.7'

services:
  bills_api:
    build:
      context: .
    volumes:
      - static_data: /vol/static
    environment:
      - SECRET_KEY=MY_SECRET_KEY983
      - ALLOWED_HOSTS=127.0.0.1,localhost

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data: /vol/static
    ports:
    - "9800:9800"
    depends_on:
      - bills_api

volumes:
  static_data:
