version: '3.7'

services:
  bills_api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./bills_api:/bills_api
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1