# Generated by Django 3.0.8 on 2021-03-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_worker_is_admin'),
        ('bill', '0002_auto_20210318_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Subscription'),
        ),
    ]
