# Generated by Django 3.0.8 on 2021-05-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('tel', models.CharField(default='', max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('token', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
